[package]
name = "winelounge"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4"
rand = "0.8"

[dependencies.sdl2]
version = "0.35"
features = ["image", "ttf"]